name: gg_music_xml_player
description: Reads music XML files and plays out note events in real time.
version: 1.0.0+beta.1
homepage: https://github.com/inlavigo/gg_music_xml_player
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  fake_async: ^1.3.1
  gg_value: ^1.3.6+4
  gg_time_controller: ^1.0.0
  music_xml:
    git:
      url: git@github.com:de-men/music_xml.git
      ref: main

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0

  flutter_lints: ^2.0.1
