name: gg_music_xml_player
description: Reads music XML files and plays out note events in real time.
version: 1.0.1
homepage: https://github.com/inlavigo/gg_music_xml_player
repository: https://github.com/inlavigo/gg_music_xml_player

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  collection: ^1.16.0
  fake_async: ^1.3.1
  gg_periodic_timer: ^1.0.0
  gg_timeline: ^1.0.1
  gg_time_controller: ^1.0.1
  gg_typedefs: ^1.0.1
  gg_value: ^1.5.0
  music_xml: ^1.2.2

dev_dependencies:
  args: ^2.4.2
  lints: ^3.0.0
  mocktail: ^1.0.3
  pana: ^0.21.45
  test: ^1.16.0
