name: gg_music_xml_player
description: Reads music XML files and plays out note events in real time.
version: 1.0.0+beta.1
homepage: https://github.com/inlavigo/gg_music_xml_player
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  fake_async: ^1.3.1
  gg_periodic_timer: ^1.0.0+beta.1
  gg_timeline:
    path: "../gg_timeline"
    # git:
    #   url: git@github.com:inlavigo/gg_timeline.git
    #   ref: ea0f9691cec8a9a4ded774d620181a3f38e01ee7
  gg_time_controller: ^1.0.0+beta.9
  gg_typedefs: ^1.0.0+beta.1
  gg_value: ^1.3.6+4

  music_xml:
    ^1.2.0
    # path: ../music_xml
    # git:
    #   url: git@github.com:de-men/music_xml.git
    #   ref: d4690bf8268c787641302041b128339f7cd74dfe

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0

  flutter_lints: ^2.0.1
